// Test account definitions. Column values are deliberately restricted to the
// migration baseline VERIFIED against prod (00001–00007, per CLAUDE.md) so the
// direct writes cannot fail on an unapplied migration. workout_profile (00014)
// is the one exception and is written separately with graceful failure.

const YEAR = new Date().getFullYear();

export const ACCOUNTS = [
  {
    key: "solo-loss",
    label: "Solo mom — fat loss, meals only",
    workout: false,
    profile: {
      display_name: "نورة",
      sex: "female",
      member_type: "adult",
      birth_year: YEAR - 34,
      height_cm: 162,
      weight_kg: 78,
      activity_level: "light",
      primary_goal: "fat_loss",
      cuisine_preference: "khaleeji",
      dietary_restrictions: [],
      has_medical_conditions: false,
      medical_conditions: [],
      is_pregnant: false,
      pregnancy_trimester: null,
      high_risk_pregnancy: false,
      consulted_doctor: true,
      allergies: [],
      dislikes: ["كبدة"],
      preferred_language: "ar",
    },
    members: [],
  },
  {
    key: "family-workout",
    label: "Mom + child + housekeeper — meals + workout opt-in",
    workout: true,
    profile: {
      display_name: "هند",
      sex: "female",
      member_type: "adult",
      birth_year: YEAR - 39,
      height_cm: 168,
      weight_kg: 71,
      activity_level: "moderate",
      primary_goal: "general_health",
      cuisine_preference: "khaleeji",
      dietary_restrictions: [],
      has_medical_conditions: false,
      medical_conditions: [],
      is_pregnant: false,
      pregnancy_trimester: null,
      high_risk_pregnancy: false,
      consulted_doctor: true,
      allergies: [],
      dislikes: [],
      preferred_language: "ar",
    },
    members: [
      {
        name: "سارة",
        role: "daughter",
        member_type: "child",
        sex: "female",
        birth_year: YEAR - 9,
        height_cm: 132,
        weight_kg: 29,
        activity_level: "active",
        primary_goal: "child_growth",
        preferred_language: "ar",
        dietary_restrictions: [],
        medical_conditions: [],
        allergies: [],
        dislikes: ["سمك"],
        consulted_doctor: false,
        school_meal_handling: "packed",
        picky_eater: true,
        display_order: 1,
        meal_mode: "shared",
      },
      {
        name: "ماريا",
        role: "housekeeper",
        member_type: "adult",
        sex: "female",
        birth_year: YEAR - 31,
        height_cm: 155,
        weight_kg: 58,
        activity_level: "active",
        primary_goal: "maintain",
        preferred_language: "tl",
        dietary_restrictions: [],
        medical_conditions: [],
        allergies: [],
        dislikes: [],
        consulted_doctor: false,
        display_order: 2,
        meal_mode: "shared",
      },
    ],
    // 00014 column — written best-effort, reported if the migration is missing.
    workout_profile: {
      location: "home",
      equipment: ["dumbbells", "bands"],
      injuries: [],
      injury_notes: null,
      desired_days: 3,
      preferred_days: [0, 2, 4],
      focus_areas: ["full_body", "core"],
      experience: "beginner",
      session_minutes: "m30_45",
    },
  },
  {
    key: "pregnant",
    label: "Pregnant mom (T2) — meals only",
    workout: false,
    profile: {
      display_name: "لطيفة",
      sex: "female",
      member_type: "pregnant",
      birth_year: YEAR - 29,
      height_cm: 165,
      weight_kg: 68,
      activity_level: "light",
      primary_goal: "pregnancy_lactation",
      cuisine_preference: "khaleeji",
      dietary_restrictions: [],
      has_medical_conditions: false,
      medical_conditions: [],
      is_pregnant: true,
      pregnancy_trimester: 2,
      high_risk_pregnancy: false,
      consulted_doctor: true,
      allergies: [],
      dislikes: [],
      preferred_language: "ar",
    },
    members: [],
  },
];
